#include<iostream>

#define PI 3.14159
#define NEWLINE std::cout<<"New Line Inserted"<<std::endl; \
	std::cout<<"Extra Line 1"<<std::endl; \
	std::cout<<"Extra Line 2"<<std::endl

int main(){


	std::cout << PI<<" ";
	NEWLINE;


	system("pause");
	return 0;
}
/*
We can use the preprocessor for example to check the current plaform.


These lines are not program statements but directives for the preprocessor.
The preprocessor examines the code before actual compilation of code begins and resolves all these directives before any code is actually generated by regular statements.


These preprocessor directives extend only across a single line of code. As soon as a newline character is found,
the preprocessor directive is ends. No semicolon (;) is expected at the end of a preprocessor directive.
The only way a preprocessor directive can extend through more than one line is by preceding the newline character at the end of the line by a backslash (\).
*/